### ISSUE TITLE
Initial agent configuration escapes colons for serverUrl in buildAgent.properties

### ISSUE THREAD

**Issue by megamorf** [JetBrains/teamcity-docker-minimal-agent#11]
Here's a docker-compose file to repro my setup:

```yaml
version: "2"
services:
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    volumes:
      - ./teamcity_server/datadir:/data/teamcity_server/datadir
      - ./teamcity_server/logs:/opt/teamcity/logs
    expose:
      - 8111
    ports:
      - 8111:8111

  teamcity-mini-agent:
    image: jetbrains/teamcity-minimal-agent:latest
    container_name: teamcity-mini-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=mini-agent
    volumes:
      - ./teamcity_mini_agent/conf:/data/teamcity_agent/conf
    links:
      - teamcity-server
```

So save that as `Docker-compose.yml` and do a `docker-compose up -d` and wait for both containers to spin up.  You'll see that `./teamcity_mini_agent/conf/buildAgent.properties` get's created. When you check its contents you'll find this entry:

```
## The address of the TeamCity server. The same as is used to open TeamCity web interface in the browser.
## Example:  serverUrl=https://buildserver.mydomain.com:8111
serverUrl=http\://teamcity-server\:8111
```

The environment variable that's passed to the container is fine though,

`docker exec -it teamcity-mini-agent bash`, then do a `printenv` returns:

```
[...]
SERVER_URL=http://teamcity-server:8111
AGENT_NAME=agent
[...]
```

So it seems your initialization scripts try to escape the colons in the url which is not the expected format according to the commented example  in the config template. Let me know if you need more info.

```
docker version

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
